name: Test against supported Java versions

on:
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-26.04
    strategy:
      fail-fast: false
      matrix:
        distribution: [ 'temurin' ]
        version: [ '8', '11', '17', '21', '25', '27' ]
    name: Test against Java ${{ matrix.distribution }} ${{ matrix.version }}
    steps:
      - uses: actions/checkout@v7
      - name: Set up JDK
        uses: actions/setup-java@v6
        with:
          distribution: ${{ matrix.distribution }}
          java-version: ${{ matrix.version }}
          cache: 'maven'
      - name: Display Java version
        run: ./mvnw --version
      - name: Test
        run: ./mvnw verify --no-transfer-progress -Dnet.bytebuddy.experimental=true
