name: Test

on:
  push:
    branches:
      - main
    paths:
      - src/**
      - pom.xml
      - .mvn/**
      - .github/workflows/**
  pull_request:
    branches:
      - main
    paths:
      - src/**
      - pom.xml
      - .mvn/**
      - .github/workflows/**
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-26.04

    steps:
      - uses: actions/checkout@v7
      - name: Set up JDK
        uses: actions/setup-java@v6
        with:
          distribution: 'temurin'
          java-version: '25'
          cache: 'maven'
      - name: Display Java version
        run: ./mvnw --version
      - name: Test
        run: ./mvnw verify --no-transfer-progress
